### ISSUE TITLE
DA16200 for Artemis Redboards

### ISSUE THREAD

**Issue by ilucwl** [ArmDeveloperEcosystem/DA16200-WiFi-Library-for-Arduino#1]
Hi Sandeep,

Excited to find your great DA16200 library. I am currently trying to get it run on an [Artemis Redboard](https://www.sparkfun.com/products/15444) but no luck. The problem seems to be related to "RingBuf" but I might not see the wood for the trees. I wonder whether you have been working with a Redboard Artemis as well or would have any pointer? This board is powerful and really great but downward compability with Unos is an issue.
Many thanks.
Iluc

**Comment by sandeepmistry** [comment]
Hi @ilucwl,

I've been in contact with the SparkFun team, their response was as follows:

> there is a mis-configured include path and the compiler isn’t picking up RingBuffer.h.

I suggest you raise an issue with the SparkFun team here: https://github.com/sparkfun/Arduino_Apollo3 - including detailed information on the compile error.

**Comment by sandeepmistry** [comment]
Closing this and the fix needs to be in the SparkFun repo linked above.
