### ISSUE TITLE
Missing return in WiFiClass::disconnect

### ISSUE THREAD

**Issue by darianbjohnson** [ArmDeveloperEcosystem/DA16200-WiFi-Library-for-Arduino#2]
I got an error when compiling - a missing return statement in Wificlass:disconnect() [in Wifi.cpp]. I went ahead and added it; things compile/run fine now (using an Adafriut M0 Metro).

```
int WiFiClass::disconnect()
{
  if (_interface == 0) {
    this->AT("+WFQAP");
  } else {
    this->AT("+WFTAP");
  }

  _status = WL_DISCONNECTED;
  return _status; //added
}
```

**Comment by sandeepmistry** [comment]
Hi @darianbjohnson,

Thank you for raising this issue and letting us know.

I've checked the WiFi101 documentation for the [`WiFi.disconnect()` API](https://www.arduino.cc/reference/en/libraries/wifi101/wifi.disconnect/) and the API should not have a return value. I'll prepare a pull request shortly to change the return type to `void`.
