### ISSUE TITLE
Firmware update

### ISSUE THREAD

**Issue by darianbjohnson** [ArmDeveloperEcosystem/DA16200-WiFi-Library-for-Arduino#3]
I am getting a message to upgrade the firmware (when running the firmware check example). I commented out the check, and everything seems to work so far (Scan Network, WPA connect, and WifiWebClient examples).

Any thoughts on how to upgrade to the latest firmware?

**Comment by sandeepmistry** [comment]
Hi @darianbjohnson,

Would you be able to share the output of the [Tools -> CheckFirmwareVersion sketch](https://github.com/ArmDeveloperEcosystem/DA16200-WiFi-Library-for-Arduino/blob/main/examples/Tools/CheckFirmwareVersion/CheckFirmwareVersion.ino)? As well as when you purchased you shield?

The latest batch of shield has some fixes for having 0x00 bytes in received socket data and transmitting 0x08 bytes in socket data.

The new firmware can be obtained from the Dialog website: https://www.dialog-semiconductor.com/products/wi-fi/da16200-modules#tab-field_tab_content_resources (need to register)

There's a TerraTerm script that can be used the update the firmware via the `DA16200 PROG` header. Alternatively, you can place the RTOS image on a web server and use the `AT+NWOTADWSTART` AT command.

**Comment by darianbjohnson** [comment]
Sure.

Board: Adafruit M0 Metro
Shield: Sparkfun WiFi Shield DA16200
Purchase: Jan 2022 (via Digikey)

Output of results:
```
21:34:15.476 -> DA16200 firmware check.
21:34:15.476 -> 
21:34:18.447 -> Firmware version installed: 
21:34:18.447 -> Latest firmware version available : 3.1.2.0
21:34:18.447 -> 
21:34:18.447 -> Check result: NOT PASSED
21:34:18.447 ->  - The firmware version on the module does not match the
21:34:18.447 ->    version required by the library, you may experience
21:34:18.447 ->    issues or failures.
```
Note: This doesn't seem to impact functionality - at least, not the functionality that I've used so far: Scan Network, WPA connect, and WifiWebClient examples.

**Comment by sandeepmistry** [comment]
Hi @darianbjohnson,

> Note: This doesn't seem to impact functionality - at least, not the functionality that I've used so far: Scan Network, WPA connect, and WifiWebClient examples.

Those examples will run fine.

However, you will face issues with the [WiFiUdpNtpClient.ino](https://github.com/ArmDeveloperEcosystem/DA16200-WiFi-Library-for-Arduino/blob/main/examples/WiFiUdpNtpClient/WiFiUdpNtpClient.ino) example sketch - and in general if you try to send a 0x08 byte over a socket, or a server sends a 0x00 byte over a socket.

**Comment by sandeepmistry** [comment]
Closing this as answered.
