### ISSUE TITLE
No "ringbuffer" for processors other than SAMD

### ISSUE THREAD

**Issue by melmers** [ArmDeveloperEcosystem/DA16200-WiFi-Library-for-Arduino#5]
Hello,

Any chance to make this work with more processors?
Kind of limited to SAMD chips due to the ringbuffer.h not supported elsewhere.

Or help to implement the ringbuffer on other chips?

I would love to make this work with the nRF52840

**Comment by sandeepmistry** [comment]
Hi @melmers,

If you have time to make a pull request to support the nRF52840 that would be great. Do you have a link to the Arduino Core you are using for the nRF52840?

The ring buffer could be swapped out for Arduino Cores that don't include it or the Arduino Core API.

**Comment by melmers** [comment]
Hi Sandeep,

I am using the Arduino Nano 33 BLE core.
I have made a variant of that board for our setup.

I am really looking forward to working with the DA16200 :-)

Thanks for your help,
Martin Elmers

**Comment by sandeepmistry** [comment]
Hi @melmers,

Thanks for the info., could you please try the changes in pull request #6 and then provide your feedback.
