### ISSUE TITLE
Does this work with any OTA libraries, and how to use Serial2

### ISSUE THREAD

**Issue by melmers** [ArmDeveloperEcosystem/DA16200-WiFi-Library-for-Arduino#7]
I was wondering if this will work with any of the OTA upgrade libraries that you know of?

How can I start up with the DA16200 on serial2?

Thanks,
Martin

**Comment by sandeepmistry** [comment]
Hi @melmers,

> I was wondering if this will work with any of the OTA upgrade libraries that you know of?

No, this is not something I've looked into.

> How can I start up with the DA16200 on serial2?

At the moment you'll have to modify the library manual, by editing [WiF.cpp](https://github.com/ArmDeveloperEcosystem/DA16200-WiFi-Library-for-Arduino/blob/main/src/WiFi.cpp#L1114).

A changing the following line:
```
WiFiClass WiFi(SERIAL_PORT_HARDWARE, 5, 2);
```
to
```
WiFiClass WiFi(Serial2, 5, 2);
```

**Comment by melmers** [comment]
Thank you!
Martin
